// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWH-SPRjSMzLC5nV-f8oIA9A7dOe9OpD8',
    appId: '1:324646141322:web:16f01a620e4a32c0e91c73',
    messagingSenderId: '324646141322',
    projectId: 'pictogether-7b733',
    authDomain: 'pictogether-7b733.firebaseapp.com',
    storageBucket: 'pictogether-7b733.appspot.com',
    measurementId: 'G-FV9BVYZPNT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi1G5y2mwJBV5Zj8MwSZC4VtseS3ZqoCw',
    appId: '1:324646141322:android:d63abb3e1c2d9096e91c73',
    messagingSenderId: '324646141322',
    projectId: 'pictogether-7b733',
    storageBucket: 'pictogether-7b733.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR-QiFGmMJoBLGqsW5vG-zW6QndgHX3XU',
    appId: '1:324646141322:ios:1ca14bd41bcc48a7e91c73',
    messagingSenderId: '324646141322',
    projectId: 'pictogether-7b733',
    storageBucket: 'pictogether-7b733.appspot.com',
    iosClientId: '324646141322-tca3ffdqdqlob7fkk9jmsv1rl0bv41ni.apps.googleusercontent.com',
    iosBundleId: 'com.example.picTogether',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR-QiFGmMJoBLGqsW5vG-zW6QndgHX3XU',
    appId: '1:324646141322:ios:96065e7994074552e91c73',
    messagingSenderId: '324646141322',
    projectId: 'pictogether-7b733',
    storageBucket: 'pictogether-7b733.appspot.com',
    iosClientId: '324646141322-b0l4tb43c342cq2rsded35nd6k98ghba.apps.googleusercontent.com',
    iosBundleId: 'com.example.picTogether.RunnerTests',
  );
}
